# -*- coding: utf-8 -*-
"""hw5_Brendan_Sullivan_ex1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKMAQUSwU7hJA5OiTz2cn8Wh-Uf1Kkey
"""

"""
Homework 5, exercise 1
Brendan Sullivan
3/20/2023
This program creates an iterator called ReverseIter
that iterates through a list in reverse. 
"""

class ReverseIter:
  def __init__(self, list1):              #constructor for ReverseIter
    self.i = -1                               #we will use self.i for the list index; -1 will start at the last item
    self.list1 = list1                              #we will use self.n for the list itself
  def __iter__(self):
    return self
  def __next__(self):
      if abs(self.i) <= len(self.list1):      # make sure there are items left to iterate through
        result = self.list1[self.i]               #return the proper item from the list
        self.i -= 1                                         # decrement the index
        return result
      else:
        raise StopIteration()


it = ReverseIter([1, 2, 3, 4])
print(next(it))
print(next(it))
print(next(it))
print(next(it))