# -*- coding: utf-8 -*-
"""hw2_Brendan_Sullivan_ex_4.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mz1DhS4QaJluJ4-Uy_GhZ0UI0mIZmjU
"""

''' 
Homework 2, Exercise 4.2
Brendan Sullivan
2/16
This program is a random number guesser game, but with 3 different variations. The first variation is that the number is between 0 and 20. 
  The second variation is that the bounds of the number are chosen randomly
  The third variation is that the computer performs all of the guesses, not the user.
'''
import random

topBound = random.randint(50,99)
bottomBound = random.randint(0,49)

randNum = random.randint(bottomBound,topBound)       ##generate num
success = False
print("I have a number between " + str(bottomBound)+" and " + str(topBound)+", you have 10 attempts to guess it")
for i in range(10):
  guess = input()
  if (int(guess)>randNum):  ##test if user guess is high, low , or correct
    print("Too high")
  elif (int(guess)<randNum):
    print("Too low")
  else:
    print("Good job!")
    break
    success = True

if success == False:
  print("The number was "+str(randNum))             ##if they never got it, display num