# -*- coding: utf-8 -*-
"""hw2_BrendanSulliva_ex_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mz1DhS4QaJluJ4-Uy_GhZ0UI0mIZmjU

# **Exercise 1**
"""

''' 
Homework 2, Exercise 1 
Brendan Sullivan
2/16
This program performs the collatz sequence on a number provided by the user 
'''

def collatz(number) :
  returnValue = 0
  if (number % 2 == 0):
    returnValue = number // 2
  else :
    returnValue = 3*number+1

  return returnValue

inputNum = input()

result = collatz(int(inputNum))
print(result)

while (result != 1):
  result = collatz(result)
  print(result)