# -*- coding: utf-8 -*-
"""hw5_Brendan_Sullivan_ex3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11-sjfsaACFQRoQCzwMr_KrmT9NLUApgi
"""

"""
Homework 5, exercise 3
Brendan Sullivan
3/20/2023
This program uses a generator function to generate a range of values
similar to what would be generated with the range() function.
This generator function (genrange()) does not generate a list, but rather 
the individual values, so a for loop is required to get what the function 
yields.
"""

def genrange(stop, start=0, step=1):
  for int1 in range (start, stop, step):
    yield int1
  

# values from 5 to 7, stepping by 1
for int1 in(genrange(7,5,1)):
  print(int1)


# values from 0 to 20, stepping by 3
for int1 in (genrange(20, step=3)):
  print(int1)

# values from 0 to 8, stepping by 1
for int1 in (genrange(8)):
  print(int1)

