# -*- coding: utf-8 -*-
"""hw5_Brendan_Sullivan_ex2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jASKW2y3vPO9PdAd_QgQvfGQZldN60By
"""

"""
Homework 5, exercise 2
Brendan Sullivan
3/20/2023
This program uses a generator function called pyt() to 
print out the first n pythagorean triplets
"""

def integers():
  i = 1
  while True:
    yield i
    i = i + 1

def pyt():
  for m in integers():        # m starts at 1 and increments
    for n in range(1,m+1):
          a=m*m-n*n             # create a pythag. trip.
          b=2*m*n                 # got this formula from https://www.sanfoundry.com/python-program
          c=m*m+n*n           # -determine-pythagorean-triplets-range/
          if(a==0 or b==0 or c==0):
              break
          yield (a,b,c)             # return the triplet

def take(n, seq):
  seq = iter(seq)
  result = []
  try:
    for i in range(n):
      result.append(next(seq))   # append the new triplet to the result list
  except StopIteration:
    pass
  return result


  
  print(take(10,pyt()))

