# -*- coding: utf-8 -*-
"""HW4_Brendan_Sullivan_ex3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SyJS4wLm5BXFJS6WB_AHdP4wp3D9PZK_
"""

""""
Homework 4, Exercise 2
Brendan Sullivan
3/9/2022 
This program takes is a password an tests its strength. If it is at least 8 characters,
has an uppercase and lowercase letter, and a digit, then it says that the password is strong
"""
import re


eightCharRegex=re.compile(r".{8}")                 # create Regex
UppercaseRegex=re.compile(r"[A-Z]")
LowercaseRegex=re.compile("[a-z]")
DigitRegex=re.compile("[0-9]")

password=input("Enter the password you would like to test: ")        # call for input

eightCharSuccess = re.search(eightCharRegex, password)    # test the input for each of the regex

UppercaseSuccess = re.search(UppercaseRegex, password)

LowercaseSuccess = re.search(LowercaseRegex, password)

DigitSuccess = re.search(DigitRegex, password)

strong = False
if eightCharSuccess:
  if UppercaseSuccess:                     # if it passed all of the regex tests, print that it is strong
    if LowercaseSuccess:
      if DigitSuccess:
        print("The password is strong enough!")
        strong = True

if strong == False:
  print("The password was not strong enough")