# -*- coding: utf-8 -*-
"""HW4_Brendan_Sullivan_ex2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WnTeMB28bGFKieAt_YntmngaX1_pQPR8
"""

""""
Homework 4, Exercise 2
Brendan Sullivan
3/9/2022 
This program takes in a massive string and searches it for phone numbers and emails within the string.
It then returns all of the phone numbers and emails that were found.
"""


inputString=input("Paste the clipboard: ")
PNReturnString=""

for index in range (len(inputString)):
  #print("current char is " + inputString[index])
  # search for phone numbers
  if inputString[index].isnumeric():           #search for a number
    if index+11 < len(inputString):    # make sure we wont run out of range
      if inputString[index+1].isnumeric():            #
        if inputString[index+2].isnumeric():         #    Test to find 2 more digits, and then skip the next character
          if inputString[index+4].isnumeric():                     #
            if inputString[index+5].isnumeric():                   #     Test to find another 3 digits, then skip the next
              if inputString[index+6].isnumeric():                 #       
                if inputString[index+8].isnumeric():                        #
                  if inputString[index+9].isnumeric():                      #     Test to find another 4 digits
                    if inputString[index+10].isnumeric():                  #
                      if inputString[index+11].isnumeric():                #
                        for i in range (12):                                  
                          PNReturnString += inputString[index+i]           #add the phone number to the return string
                        PNReturnString += ", "                          
print("Phone numbers: " + PNReturnString)


EmailReturnString=""
splitString=inputString.split()
for word in (splitString):
  fail = False
  #print("current word is " + word)
  # search for @ sign
  for index in range (len(word)):
    if word[index] == "@":               # search for @
     # print("found @")
      hasAt=True
      hasDot=False
      i = 1
      while hasDot==False :
        if (word[index+i]) == "%":          # search for a . after the @, but make sure there are no bad characters inbetween
          fail=True
        if (word[index+i]) == "+":
          fail=True
        if (word[index+i]) == "-":
          fail=True
        if (word[index +i]) == "@":
          fail=True
        if (word[index+i]) == ".":
          hasDot = True
         # print("found dot")
          if (word[index+i +1].isalpha()):
            if (word[index+i +2].isalpha()):                   #make sure there are only 2-3 letters after the .
             # print("next two are letters")
              if ( (index +i +4) >= len(word)):
                if fail==False:
                  #print("appending")
                  EmailReturnString += word              #append the email to the return string
                  EmailReturnString += ", "
        i+=1
               
    


print("Emails: "+EmailReturnString)