# -*- coding: utf-8 -*-
"""hw2_Brendan_Sullivan_ex_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mz1DhS4QaJluJ4-Uy_GhZ0UI0mIZmjU
"""

''' 
Homework 2, Exercise 3
Brendan Sullivan
2/16
This program creates a list of objects and performs various tasks with that list, such as appending to it, removing, sorting, etc.
'''

objects = ["Wallet","Phone","Keys"]
print(objects)
objects.sort()
print("Sorted list: "+ str(objects))
print("\nFirst item: " +objects[0])
print("\nLast item: " +objects[-1])
i = objects.index("Keys")
print("\nIndex of Keys: "+ str(i))

objects.append("Tablet")
print("\nAppended Tablet: " + str(objects))

objects.insert(1,"Mask")
print("\nInserted Mask: " +str(objects))

objects.remove("Phone")
print("\nRemoved Phone: " +str(objects))

objects.reverse()
print("\nReversed List: " +str(objects))




def strList(list):
  returnString = list[0]
  for i in range (len(list)-2):
    returnString += ", "+list[i+1]

  returnString += ", and " + list[-1]
  return returnString

strList(objects)